#!/usr/bin/env python3
"""Run Kitsoki onboarding readiness checks for this checkout.

Generated by `kitsoki` project onboarding. It is intentionally explicit:
onboarding writes this file but does not run it automatically.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path


CHECKS = [
  {
    "command": "kitsoki validate .kitsoki/stories/studio-sassfully-dev/app.yaml",
    "gate": "required",
    "id": "story-load",
    "kind": "story"
  }
]


def run_check(check: dict, root: Path, timeout: int) -> dict:
    command = str(check.get("command") or "").strip()
    started = time.time()
    result = {
        "id": check.get("id", ""),
        "kind": check.get("kind", ""),
        "gate": check.get("gate", ""),
        "command": command,
        "ok": False,
        "exit_code": None,
        "duration_ms": 0,
        "stdout": "",
        "stderr": "",
    }
    if not command:
        result["stderr"] = "empty command"
        return result
    try:
        proc = subprocess.run(
            command,
            cwd=root,
            shell=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as err:
        result["duration_ms"] = int((time.time() - started) * 1000)
        result["stderr"] = f"timed out after {timeout}s"
        if err.stdout:
            result["stdout"] = err.stdout if isinstance(err.stdout, str) else err.stdout.decode("utf-8", "replace")
        if err.stderr:
            result["stderr"] += "\n" + (err.stderr if isinstance(err.stderr, str) else err.stderr.decode("utf-8", "replace"))
        return result
    result["duration_ms"] = int((time.time() - started) * 1000)
    result["exit_code"] = proc.returncode
    result["ok"] = proc.returncode == 0
    result["stdout"] = proc.stdout
    result["stderr"] = proc.stderr
    return result


def detail_for(item: dict) -> str:
    parts = []
    if item.get("exit_code") is not None:
        parts.append(f"exit={item.get('exit_code')}")
    if item.get("stderr"):
        parts.append("stderr: " + str(item.get("stderr", "")).strip().splitlines()[0][:240])
    elif item.get("stdout"):
        parts.append("stdout: " + str(item.get("stdout", "")).strip().splitlines()[0][:240])
    return "; ".join(parts) or "completed"


def yaml_scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(str(value))


def readiness_yaml(report: dict) -> str:
    lines = ["readiness:", f"  status: {yaml_scalar(report.get('status', 'not-run'))}"]
    checks = report.get("checks") if isinstance(report.get("checks"), list) else []
    if checks:
        lines.append("  checks:")
        for item in checks:
            lines.append(f"    - id: {yaml_scalar(item.get('id', ''))}")
            lines.append(f"      kind: {yaml_scalar(item.get('kind', ''))}")
            lines.append(f"      ok: {yaml_scalar(bool(item.get('ok')))}")
            detail = detail_for(item)
            if detail:
                lines.append(f"      detail: {yaml_scalar(detail)}")
    return "\n".join(lines) + "\n"


def replace_top_level_block(text: str, key: str, replacement: str) -> str:
    lines = text.splitlines()
    start = -1
    for index, line in enumerate(lines):
        if line == key + ":":
            start = index
            break
    if start == -1:
        return text.rstrip() + "\n\n" + replacement
    end = len(lines)
    for index in range(start + 1, len(lines)):
        line = lines[index]
        if line and not line.startswith((" ", "\t")):
            end = index
            break
    return "\n".join(lines[:start] + replacement.rstrip().splitlines() + lines[end:]) + "\n"


def update_profile(root: Path, report: dict) -> Path:
    profile = root / ".kitsoki" / "project-profile.yaml"
    text = profile.read_text(encoding="utf-8")
    profile.write_text(replace_top_level_block(text, "readiness", readiness_yaml(report)), encoding="utf-8")
    return profile


def main() -> int:
    parser = argparse.ArgumentParser(description="Run project onboarding readiness checks.")
    parser.add_argument("--list", action="store_true", help="print the checks without running them")
    parser.add_argument("--json", action="store_true", help="print the report JSON to stdout")
    parser.add_argument("--update-profile", action="store_true", help="persist a readiness summary into .kitsoki/project-profile.yaml")
    parser.add_argument("--timeout", type=int, default=120, help="per-check timeout in seconds")
    parser.add_argument("--out", default=".artifacts/kitsoki-readiness.json", help="report path")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    if args.list:
        print(json.dumps({"checks": CHECKS}, indent=2, sort_keys=True))
        return 0

    results = [run_check(check, root, args.timeout) for check in CHECKS]
    required_failed = [
        item for item in results
        if item.get("gate") == "required" and not item.get("ok")
    ]
    any_failed = any(not item.get("ok") for item in results)
    status = "pass"
    if required_failed:
        status = "fail"
    elif any_failed:
        status = "partial"
    report = {
        "schema": "kitsoki-readiness/v1",
        "status": status,
        "checks": results,
    }
    out = root / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    profile = None
    if args.update_profile:
        profile = update_profile(root, report)
    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(f"readiness {status}: {out}")
        if profile is not None:
            print(f"profile updated: {profile}")
        for item in results:
            mark = "PASS" if item.get("ok") else "FAIL"
            print(f"- {mark} {item.get('id')}: {item.get('command')}")
    return 1 if required_failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
